openapi: 3.0.0
info:
  title: Language skills up API
  version: 1.0.0
servers:
- url: https://d5dlmshm71fmfl4smcq6.apigw.yandexcloud.net
paths:
  /hello:
    get:
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          Content-Type: text/plain
        content:
          text/plain: |
            Hello, {username}!
      operationId: hello
      parameters:
      - description: User name to appear in greetings
        explode: true
        in: query
        name: username
        required: false
        schema:
          default: world
          type: string
        style: form
      responses:
        200:
          content:
            text/plain:
              schema:
                type: string
          description: Greeting
      summary: Say hello
  /words:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ek7ufeqvsvn8753hoq
        service_account_id: aje067mchvsmt3pcbr8r
      operationId: words
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  type: object
                type: array
          description: Another example
      summary: words operations